name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/ankit-mogha/myapp/myimage:latest
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: deployment-cluster-sdk
  GKE_NAMESPACE: demo-application
  GKE_ZONE: asia-southeast1-a

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 19
      - run: mvn compile jib:dockerBuild